title: Seyi Williams Olowookere
logo: Sheyi.jpeg
description: A Finance & Data professional with 5+ years experience. Skilled in SQL, Power BI, Excel, SAP, Xero. I turn financial data into actionable insights.
# show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal
