title: Seyi Williams Olowookere
logo: download.jfif
description: A Data Analyst about 2 years experience in Report Automation using Advanced Excel, Data Manipulation and Interogation on SQL and Business Intelligence Report on Power BI.
# show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal
